'''
002 Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

if __name__ == '__main__':
    #create list of fibonacci numbers
    fib_list=[1,2]
    # create running total of evens
    total = 2

    while(True):
        new_num = fib_list[-1] + fib_list[-2]
        if new_num > 4000000:
            break
        else:
            fib_list.append(new_num)
            if new_num%2==0:
                total+=new_num

    print(total)
