/*
002 Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>
#include <vector>
int main() {
  std::vector<int> fib_list;
  fib_list.push_back(1);
  fib_list.push_back(2);
  int total;
  int new_num;
  total = 2;

  while(true){
    new_num=fib_list.end()[-1] + fib_list.end()[-2];
    if(new_num > 4000000){
      break;
    }
    else {
      fib_list.push_back(new_num);
      if(new_num%2==0){
        total += new_num;
      }
    }
  }
  std::cout << total << std::endl;
  return 0;
}
